// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"project_layout/internal/conf"
	"project_layout/internal/data"
	"project_layout/internal/pkg"
	"project_layout/internal/server"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config) *pkg.App {
	serverServer := server.NewMyServer(cfg)
	dataSource := data.NewMySQL(cfg)
	app := newApp(serverServer, dataSource)
	return app
}
